"""
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""

import random
import string

value_of_s = input("s: ")
s = value_of_s
extra = random.choice(string.ascii_lowercase)

chars = list(value_of_s) + [extra]
random.shuffle(chars) 
t = "".join(chars)

# Approch 1
for char in t:
    # print(char)
    if char not in s:
        print(char)

# Approch 2
result = 0
for char in t:
    result ^= ord(char)

for char in s:
    result ^= ord(char)

print(chr(result))